export default [
  {
    id: "twinpeaksrogers",
    name: "Twin Peaks",
    location: "Rogers",
    website: "https://twinpeaksrestaurant.com/locations/rogers-ar",
    facebook: "https://www.facebook.com/TwinPeaksRogers/",
    instagram: "https://www.instagram.com/rogerstwinpeaks/",
    googleMap:
      "https://www.google.com/maps/place/Twin+Peaks+Rogers/@36.3011917,-94.1738379,15z/data=!4m5!3m4!1s0x0:0xca20801366951863!8m2!3d36.3011917!4d-94.1738379",
    specials: {
      monday: ["$3 22oz Domestic Brews", "$4 Mules", "$5 Cheeseburgers"],
      tuesday: [
        "$3 22oz Mexican Bews",
        "$4 Peaks Margarita",
        "$5 All Tacos (no modifications)",
        "$15 Import Buckets",
      ],
      wednesday: [
        "$3 22oz Twin Peaks Brew",
        "$4 Tito's Tea",
        "$5 Texas Philly & Fries",
        "$15 Import Buckets",
      ],
      thursday: [
        "$3 22oz Twin Peaks Brews",
        "$3 22oz Domestic Brews",
        "$5 Irish Trash Can",
        "$7 All Chicken Sandwiches",
        "$15 Import Buckets",
      ],
      friday: [],
      saturday: [
        "$3 Mimosas",
        "$5 Sangrias",
        "$10 Peaks Sampler",
        "$15 Import Buckets",
      ],
      sunday: [
        "$3 Mimosas",
        "$5 Sangrias",
        "$10 Peaks Sampler",
        "$15 Import Buckets",
      ],
    },
    happyHours: [
      {
        time: "3-6pm",
        specials: [
          "1/2 Off Appetizers",
          "$1.50  10oz Domestic Brews",
          "$2.50  10oz Twin Peaks Brews",
          "$3 22oz Domestic Brews",
          "$4.50  22oz Twin Peaks Brews",
        ],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
      {
        time: "10pm-Close: Midnight Munchies!",
        specials: [
          "$2 22oz Twin Peaks Brews",
          "$3 22oz Domestic Brews",
          "$6 All Handhelds",
        ],
        dow: ["sunday", "monday", "tuesday", "wednesday", "thursday"],
      },
      {
        time: "All Day, Every Day!",
        specials: ["$10 Domestic Buckets", "$15 Import Buckets"],
        dow: [
          "saturday",
          "sunday",
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday",
        ],
      },
    ],
  },
  {
    id: "smittysrogers",
    name: "Smitty's Garage",
    location: "Rogers",
    website: "https://eatatthegarage.com/locations/smittys-rogers/",
    facebook: "https://www.facebook.com/smittysgaragerogers/",
    instagram: "https://www.instagram.com/thegarage_burgers/",
    googleMap: "https://goo.gl/maps/YXqbVjKDR5Af3jtt8",
    specials: {
      monday: [],
      tuesday: [],
      wednesday: [],
      thursday: [],
      friday: [],
      saturday: [],
      sunday: [],
    },
    happyHours: [
      {
        time: "3-6pm",
        specials: [
          "$2 Domestics",
          "$3 House Wines",
          "$4.99 Specialty Cocktails",
        ],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
    ],
  },
  {
    id: "after5rogers",
    name: "After 5 Bar & Grill",
    location: "Rogers",
    website: "",
    facebook: "https://www.facebook.com/guccigasstation/",
    instagram:
      "https://www.instagram.com/explore/locations/162865594322800/after-5-bar-grill/",
    googleMap: "https://goo.gl/maps/ExRnsk63bZQwjuQJ9",
    specials: {
      monday: ["$2.50 Drafts", "$.50 off Craft Bottles"],
      tuesday: ["$1 Domestic Bottles"],
      wednesday: ["$2 Whiteclaw/Truly", "$2.50 Wine"],
      thursday: ["$5 Jack Daniels, Jameson, and Crown Royal"],
      friday: ["$3 Fireball Shots", "$3 Well Drinks"],
      saturday: ["$2.50 Wine", "$2.50 Drafts", "$3 Well Drinks"],
      sunday: [],
    },
    happyHours: [],
  },

  {
    id: "gusanosbentonville",
    name: "Gusano's",
    location: "Bentonville",
    website: "https://gusanos.pizza/bentonville/",
    facebook:
      "https://www.facebook.com/Gusanos-Chicago-Style-Pizzeria-109101070783045/",
    instagram:
      "https://www.instagram.com/explore/locations/138576752827437/gusanos-chicago-style-pizzeria-bentonville-ar/",
    googleMap: "https://goo.gl/maps/gE3hRqDaW2rUXfi28",
    specials: {
      monday: ["$6.50 Domestic Pitchers"],
      tuesday: ["$2 Domestic Bottles"],
      wednesday: ["$10 Craft Pitchers"],
      thursday: ["All Day Happy Hour"],
      friday: ["$3 House Wines"],
      saturday: ["$6.50 Domestic Pitchers", "$2 Domestic Drafts"],
      sunday: [
        "$2 Mimosas",
        "$2 Bloody Marys",
        "$2 Screwdrivers",
        "$12 Domestic Buckets",
      ],
    },
    happyHours: [
      {
        time: "3-7pm",
        specials: ["$1 off Drafts", "$1 off Wells", "$1 off Wines"],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
      {
        time: "5-6pm: Happiest Hour!",
        specials: ["$1 12oz Domestic Drafts", "$2 22oz Domestic Drafts"],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
    ],
  },
  {
    id: "jjsrogers",
    name: "JJ's Grill",
    location: "Rogers",
    website: "http://jjsgrill.com/locations/jjs-rogers/",
    facebook: "https://www.facebook.com/JJsGrillRogers/",
    instagram: "https://www.instagram.com/jjsgrill/",
    googleMap: "https://goo.gl/maps/hWm41PP4QhZ3bGWZA",
    specials: {
      monday: [
        "$5 Moscow or Kentucky Mule",
        "$2.50 JJ's Light Draft",
        "$1.99 Frozen Margaritas",
      ],
      tuesday: [
        "$3 JJ's Seasonal Draft",
        "$3.50 House Wine",
        "$1.99 Frozen Margaritas",
      ],
      wednesday: [
        "$3.50 Jack & Coke",
        "$2.50 Shock Top Draft",
        "$1.99 Frozen Margaritas",
      ],
      thursday: [
        "$3 Long Island Tea",
        "$3 JJ's Red Draft",
        "$1.99 Frozen Margaritas",
      ],
      friday: [
        "$5 JJ's Dirty Shirley",
        "$3 JJ's IPA Draft",
        "$3 Fireball Shot",
        "$1.99 Frozen Margaritas",
      ],
      saturday: [
        "$5 Smithworks Bloody Mary",
        "$3 JJ's Rasp Wheat",
        "$3 JJ's McFizzle Shot",
        "$1.99 Frozen Margaritas",
      ],
      sunday: [
        "$5 Smithworks Bloody Mary",
        "$12 Mimosa Bucket",
        "$5 Breakfast Shot",
        "$1.99 Frozen Margaritas",
      ],
    },
    happyHours: [
      {
        time: "3-6pm",
        specials: [
          "$2 Domestic Pints",
          "$3 Other Pints",
          "$.50 off All Bottled Beer",
          "$2 All Well Drinks",
          "$2.50 All House Wine (Glasses)",
          "$5 3 Cheeseburger Sliders",
          "$5 5 Strips 'n 5 Wings",
          "$25 25 Strips 'n 25 Wings",
        ],
        dow: [
          "sunday",
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday",
          "saturday",
        ],
      },
      {
        time: "3:00-3:20 | 4:20-4:40 | 5:40-6:00",
        specials: ["$1 Select JJ's Brewing Co. Drafts"],
        dow: [
          "sunday",
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday",
          "saturday",
        ],
      },
    ],
  },

  {
    id: "davebustersrogers",
    name: "Dave & Buster's",
    location: "Rogers",
    website: "https://www.daveandbusters.com/locations/rogers",
    facebook: "https://www.facebook.com/DnBRogersAR",
    instagram: "https://www.instagram.com/daveandbusters/",
    googleMap: "https://goo.gl/maps/ProinniHCWE2MdUQA",
    specials: {
      monday: ["$19.99 Unlimited Wings & Video Games"],
      tuesday: [
        "$2 Corona/Corona Light & 2 FREE Game Plays with $10 Power Card purchase",
      ],
      wednesday: ["1/2 Price Games"],
      thursday: ["$19.99 Unlimited Wings & Video Games"],
      friday: [],
      saturday: [],
      sunday: ["$19.99 Unlimited Wings & Video Games"],
    },
    happyHours: [
      {
        time: "3-7pm",
        specials: [
          "$2.50 Domestic Pints",
          "1/2 Cocktails",
          "$1 off 22oz Drafts",
          "$1 off Wine Glasses",
          "$3 off Wine Bottles",
          "$5 Bites - Asian Chicken Wonton Nachos, Mexican Street Corn Quesadilla, Bavarian Pretzels, Loaded Pot Stickers, Guacamole & Chips",
        ],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
      {
        time: "9pm-Midnight",
        specials: [
          "$2.50 Domestic Pints",
          "1/2 Cocktails",
          "$1 off 22pz Drafts",
          "$1 off Wine Glasses",
          "$3 off Wine Bottles",
          "$5 Bites - Asian Chicken Wonton Nachos, Mexican Street Corn Quesadilla, Bavarian Pretzels, Loaded Pot Stickers, Guacamole & Chips",
        ],
        dow: ["sunday", "monday", "tuesday", "wednesday", "thursday"],
      },
    ],
  },
  {
    id: "boarsnestrogers",
    name: "Boars' Nest",
    location: "Rogers",
    website: "https://www.boarsnestnwa.com/",
    facebook: "https://www.facebook.com/boarsnestrogers/",
    instagram:
      "https://www.instagram.com/explore/locations/169354685/boars-nest-rogers/",
    googleMap: "https://g.page/boarsnestrogers?share",
    specials: {
      monday: ["$1.25 Wings", "$6 32oz Mug ($3 Domestic / $4 Craft Refills)"],
      tuesday: ["All Day Happy Hour", "$5.99 Street Taco Basket"],
      wednesday: ["$1.50 Ribs", "$2.25 Domestic Bottles"],
      thursday: [
        "$1 Off Burgers",
        "$10 Domestic Buckets",
        "$15 Mexican Buckets",
      ],
      friday: ["$1 Off All Craft Beers", "$14 Margarita Pitchers"],
      saturday: [
        "$1.50 Ribs",
        "$4 Boys (Jim, Jack, Johnny & Jose)",
        "$10 Domestic Buckets",
        "$15 Mexican Buckets",
      ],
      sunday: ["$3 Bloody Mary's and Mimosa's", "$2 Millers"],
    },
    happyHours: [
      {
        time: "3-8pm",
        specials: [
          "$2.25 Domestic bottles",
          "$2.50 Wine",
          "$2.50 Wells",
          "1/2 price Appetizers",
        ],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
      {
        time: "11am-3pm",
        specials: [
          "$2.25 Domestic bottles",
          "$2.50 Wine",
          "$2.50 Wells",
          "1/2 price Appetizers",
        ],
        dow: ["saturday"],
      },
    ],
  },
  {
    id: "johnnycarinosrogers",
    name: "Johnny Carinos",
    location: "Rogers",
    website: "https://www.carinos.com/rogers-ar/location/detail",
    facebook: "https://www.facebook.com/pg/carinositalian",
    instagram: "https://www.instagram.com/johnnycarinos/",
    googleMap: "https://goo.gl/maps/42pTt3LQzuhkW9136",
    specials: {
      monday: ["$3 Well Drinks", "2 for 1 Regular Pizzas"],
      tuesday: ["$2 Johnny's Margarita", "$.50 Sweet Chili Shrimp"],
      wednesday: [
        "$2 Short Premium Drafts",
        "$.50 Plain & Simple Boneless Wings",
        "Seasoned Wings Add $.05",
        "Sauced Wings Add $.25",
      ],
      thursday: [
        "$5 Gande Bellini",
        "$.25 Plain & Simple Traditional Wings",
        "$.25 Plain & Simple Boneless Wings",
        "Seasoned Wings Add $.05",
        "Sauced Wings Add $.25",
      ],
      friday: ["$6 Carinorita", "$5 Calamari"],
      saturday: [
        "$3 Strawberry Margarita",
        "$4 Italian Nachos - Add Chicken, Sausage, or Combo for $1",
      ],
      sunday: [
        "$5 Michelada",
        "$6 Fried Mozzarella + Italian Nachos - Add Chicken, Sausage, or Combo for $1",
      ],
    },
    happyHours: [],
  },
  {
    id: "foghornsrogers",
    name: "Foghorn's Wings",
    location: "Rogers",
    website: "https://www.foghornswings.com/",
    facebook: "https://www.facebook.com/foghorns4/",
    instagram:
      "https://www.instagram.com/explore/locations/586357318200574/foghorns-rogers/",
    googleMap: "https://goo.gl/maps/TUiCqbTaAQNYtfKw8",
    specials: {
      monday: ["$2 Off Any Burger w/ Side"],
      tuesday: ["$.79 Wings (Traditional or Boneless)"],
      wednesday: ["Kids Eat Free (w/ Adult Meal)", "$1 Off All Bottled Beer"],
      thursday: ["$.79 Boneless Wings"],
      friday: ["$3.50 Fireball Shots"],
      saturday: [
        "$3 Well Bloody Marys and Mimosas",
        "$4 Flavored Vodka Bloody Marys",
        "$5 Premium Vodka Bloody Marys",
      ],
      sunday: [
        "$3 Well Bloody Marys and Mimosas",
        "$4 Flavored Vodka Bloody Marys",
        "$5 Premium Vodka Bloody Marys",
      ],
    },
    happyHours: [
      {
        time: "3-6pm",
        specials: [
          "$2.50 Domestic Drafts",
          "$1 off Wine",
          "$1 off Well Liquor",
          "$1 off Appetizers",
          "$.50 off All Bottled Beer",
        ],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
      {
        time: "8-9pm",
        specials: ["$2.50 Domestic Drafts", "$2.50 Wells"],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
      {
        time: "11am-3pm",
        specials: [
          "$2.25 Domestic bottles",
          "$2.50 Wine",
          "$2.50 Wells",
          "1/2 price Appetizers",
        ],
        dow: ["saturday"],
      },
    ],
  },
  {
    id: "pressroombentonville",
    name: "Pressroom",
    location: "Bentonville",
    website: "http://www.eatatpressroom.com/",
    facebook: "https://www.facebook.com/eatatpressroom/",
    instagram: "https://www.instagram.com/eatatpressroom/",
    googleMap: "https://goo.gl/maps/tpxwAo1aKgTz1sZMA",
    specials: {
      monday: [],
      tuesday: [],
      wednesday: [],
      thursday: [],
      friday: [],
      saturday: [],
      sunday: [],
    },
    happyHours: [
      {
        time: "3pm-6pm",
        specials: ["It's a mystery!"],
        dow: [
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday",
          "saturday",
        ],
      },
    ],
  },
  {
    id: "johnnybruscosbentonville",
    name: "Johnny Brusco's",
    location: "Bentonville",
    website: "https://johnnybruscos.com/location/bentonville/",
    facebook: "https://www.facebook.com/JohnnyBruscosBentonville/",
    instagram:
      "https://www.instagram.com/explore/locations/16432931/johnny-bruscos-new-york-style-pizza-delivery-available-curbside-pickup-available/",
    googleMap: "https://goo.gl/maps/RLtKrCJ93vnduErD6",
    specials: {
      monday: [
        "Buy any Large Specialty Pizza and get a FREE Kids Spaghetti with Marinara Sauce. (Dine in only)",
      ],
      tuesday: ["$1 cheese slice (after 4pm)"],
      wednesday: ["$.75 Wings (Dine in only)", "$4 glasses of wine"],
      thursday: ["Sandwich chip/fries and drink $7.99"],
      friday: [],
      saturday: ["$9.99 16in Regular 1-Topping Pizza (11-5pm Dine in only)"],
      sunday: [],
    },
    happyHours: [
      {
        time: "2pm-5pm",
        specials: ["1/2 Price Appetizers!"],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
      {
        time: "All Day, Every Day!",
        specials: [
          "$2.50 22oz Coors Light",
          '$25.99 - "Family Special" – Large Regular 1-Topping, Garlic Knots (or Cheese Bread Stix, and 2 Small Garden Salads',
        ],
        dow: [
          "saturday",
          "sunday",
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday",
        ],
      },
    ],
  },
  {
    id: "bikerack8thstbentonville",
    name: "Bike Rack Brewing Co. (8th St)",
    location: "Bentonville",
    website: "http://bikerackbrewing.com/",
    facebook: "https://www.facebook.com/bikerackbrewing/",
    instagram: "https://www.instagram.com/bikerackbrewingco",
    googleMap: "https://goo.gl/maps/pM99faooe26fe6wp7",
    specials: {
      monday: ["$10 Growler Refills"],
      tuesday: ["$10 Growler Refills"],
      wednesday: [],
      thursday: [],
      friday: [],
      saturday: [],
      sunday: ["$10 Growler Refills", "$5 off Cases to Go"],
    },
    happyHours: [
      {
        time: "5pm-7pm",
        specials: ["$3 Golden, Amber and Stout pints"],
        dow: ["monday", "tuesday", "thursday"],
      },
    ],
  },
  {
    id: "bigwhiskeysbentonville",
    name: "Big Whiskey's",
    location: "Bentonville",
    website: "https://bigwhiskeys.com/location/bentonville-ar/",
    facebook: "https://www.facebook.com/bigwhiskeysbentonville/",
    instagram: "https://instagram.com/big.whiskeys",
    googleMap: "https://goo.gl/maps/s3dxyaPJZv2BL4tb8",
    specials: {
      monday: ["After 6pm: $12 Domestic Buckets"],
      tuesday: [
        "After 6pm: $5 Stir Crazy",
        "Free Kids Meal with the Purchase of an Adult Entree",
      ],
      wednesday: ["After 6pm: $6 Fishbowl"],
      thursday: ["After 6pm: $5 Martini's"],
      friday: ["After 6pm: $6 Old Fashioned"],
      saturday: ["$2 off Flights"],
      sunday: ["$2.50 Domestics", "$3.50 Craft/Import Drafts"],
    },
    happyHours: [
      {
        time: "4-6pm",
        specials: ["$2 Domestic Pints", "$3 Craft Pints", "$5 Appetizers"],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
    ],
  },
  {
    id: "beefobradysbentonville",
    name: "Beef O'Brady's",
    location: "Bentonville",
    website: "https://www.beefobradys.com/Bentonville",
    facebook:
      "https://www.facebook.com/Bentonville-Beef-O-Bradys-141251309228133/",
    instagram: "https://www.instagram.com/beefobradys1985",
    googleMap: "https://goo.gl/maps/jYqANLZYDgKW2uM38",
    specials: {
      monday: ["$5.99 Build Your Own Burger + Fries"],
      tuesday: [
        "$5.99  2 Tacos + Chips & Salsa",
        "$1.99 Kid's Meal (Side, Drink, & Treat) for Those 12 and Younger",
      ],
      wednesday: [
        "Wing Wednesday!",
        "$.59 Boneless Wings",
        "$.79 Traditional Wings",
      ],
      thursday: [
        "$9.99 Fajitas (Chicken, Angus Skirt Steak, or Grilled Shrimp)",
      ],
      friday: ["$12.99 Sirloin & Grilled (or Fried) Shrimp + Fries & Salad"],
      saturday: ["$13.99+ 3 Course Meals"],
      sunday: ["Double Beef Reward Points"],
    },
    happyHours: [
      {
        time: "4-7pm",
        specials: [
          "$2.25 All Domestic Drafts",
          "$3 House Wines",
          "$3 Well Drinks",
          "$4 Select Premium Drafts",
          "$4 Angry Onion, Mini Chicken Quesadilla, Nashville Hot Cheese Fries",
          "$5 2 Mini Chicken Tacos w/ Chips & Salsa",
          "$6 2 Mini Beef Tacos w/ Chips & Salsa, Irish Nachos, 8PC Boom Boom Shrimp",
        ],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
      {
        time: "All Day, Every Day!",
        specials: ["$1.50 16oz Beef's 35 Lager", "$2.50 22oz Beef's 35 Lager"],
        dow: [
          "saturday",
          "sunday",
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday",
        ],
      },
    ],
  },
  {
    id: "tuskandtrotterbentonville",
    name: "Tusk & Trotter",
    location: "Bentonville",
    website: "http://tuskandtrotter.com/",
    facebook: "https://www.facebook.com/TuskandTrotter/",
    instagram: "https://www.instagram.com/tuskandtrotter",
    googleMap: "https://goo.gl/maps/BkJo5AK7zJWRfJCr9",
    specials: {
      monday: [],
      tuesday: [],
      wednesday: [],
      thursday: [],
      friday: [],
      saturday: [],
      sunday: [],
    },
    happyHours: [
      {
        time: "4-6pm",
        specials: [
          "$3 Arkansas Fritters",
          "$3 Basket of Pork Rinds",
          "$3 Basket of Pommes Frites",
        ],
        dow: ["wednesday", "thursday", "friday"],
      },
    ],
  },
  {
    id: "firstseatbentonville",
    name: "The First Seat Pub & Grill",
    location: "Bentonville",
    website: "",
    facebook: "https://www.facebook.com/thefirstseat/",
    instagram: "https://www.instagram.com/thefirstseat/",
    googleMap: "https://goo.gl/maps/1Uh2YfYQ2TxkwoBh7",
    specials: {
      monday: [],
      tuesday: [],
      wednesday: [],
      thursday: [],
      friday: [],
      saturday: [],
      sunday: [],
    },
    happyHours: [
      {
        time: "4-7pm",
        specials: [
          "$.50 off Draft Beer",
          "$2.50 Domestic Beers",
          "$4 House Wine",
          "$4 Well Drinks",
        ],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
    ],
  },
  {
    id: "pedalerspubbentonville",
    name: "The Pedaler's Pub",
    location: "Bentonville",
    website: "http://www.pedalerspub.com/",
    facebook: "https://www.facebook.com/PedalersPub/",
    instagram:
      "https://www.instagram.com/explore/locations/924679534/pedalers-pub/",
    googleMap: "https://goo.gl/maps/riWjhuPZ8SmaxdEe9",
    specials: {
      monday: [],
      tuesday: [],
      wednesday: [],
      thursday: [],
      friday: [],
      saturday: [],
      sunday: [],
    },
    happyHours: [
      {
        time: "4-6pm",
        specials: ["$3 Wells", "$3 Rotating Draft Beers", "$5 Draft Wine"],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
      {
        time: "11-4pm",
        specials: ["$5 Bloody Marys"],
        dow: ["saturday", "sunday"],
      },
    ],
  },
  {
    id: "thehollerbentonville",
    name: "The Holler",
    location: "Bentonville",
    website: "https://www.alocalhangout.com/",
    facebook: "https://www.facebook.com/thehollerbentonville/",
    instagram: "https://www.instagram.com/thehollerbentonville/",
    googleMap: "https://goo.gl/maps/mrMahCCrUnvJWedt6",
    specials: {
      monday: [],
      tuesday: [],
      wednesday: [],
      thursday: [],
      friday: [],
      saturday: [],
      sunday: [],
    },
    happyHours: [
      {
        time: "3-6pm",
        specials: [
          "$6 House White Wine",
          "$6 House Red Wine",
          "$2 PBR Tall Boy",
          "$6 Frozen Rotational's",
          "Old Grandad Shot",
        ],
        dow: [
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday",
          "saturday",
        ],
      },
    ],
  },
  {
    id: "scotchandsodabentonville",
    name: "Scotch & Soda",
    location: "Bentonville",
    website: "http://www.thescotchandsoda.com/bentonville-menus/",
    facebook: "https://www.facebook.com/thescotchandsodabentonville/",
    instagram: "https://www.instagram.com/thescotchandsodabv/",
    googleMap: "https://goo.gl/maps/4Bdn3RDLx1mGS26r5",
    specials: {
      monday: [],
      tuesday: [],
      wednesday: [],
      thursday: [],
      friday: [],
      saturday: [],
      sunday: [],
    },
    happyHours: [
      {
        time: "4-6pm",
        specials: [
          "$1 off All Classics",
          "$1 off All Draft Beers",
          "$1 off All Small Plates",
        ],
        dow: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      },
    ],
  },
  {
    id: "bvbarandgrillbellavista",
    name: "BV Bar & Grill",
    location: "Bella Vista",
    website: "https://bvbarandgrill.com/",
    facebook: "https://www.facebook.com/bvbarandgrill/",
    instagram: "https://www.instagram.com/bv_bar_and_grill/",
    googleMap: "https://goo.gl/maps/sLjDfM7MonfdgDyc6",
    specials: {
      monday: ["$20 for 2 Meals"],
      tuesday: ["$20 Prime Rib Special (3pm Until Sold Out)"],
      wednesday: ["Chicken Wings + POA Discount (After 4pm?)"],
      thursday: ["$12 Chicken Fried Steak"],
      friday: [],
      saturday: [],
      sunday: [],
    },
    happyHours: [
      {
        time: "All Day!",
        specials: ["$3 Wines", "$3 Wells", "$3 Brews"],
        dow: [
          "saturday",
          "sunday",
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday",
        ],
      },
      {
        time: "3-6pm",
        specials: ["1/2 Price Appetizers"],
        dow: ["friday"],
      },
    ],
  },
  {
    name: "Highlands Golf & Pub",
    location: "Bella Vista",
    website: "https://bellavistapoa.com/thingstodo/golf/#highlands",
    facebook: "https://www.facebook.com/highlandsgolfpub/",
    instagram:
      "https://www.instagram.com/explore/locations/1016157052/highlands-golf-course-bella-vista/",
    googleMap: "https://goo.gl/maps/AhHER5853EoZ9asJ9",
    specials: {
      monday: [],
      tuesday: [],
      wednesday: [],
      thursday: [],
      friday: [],
      saturday: [],
      sunday: [],
    },
    happyHours: [
      {
        time: "11am--8pm",
        specials: [
          "$2 House Spirits",
          "$2 16oz Domestic Drafts",
          "$3 House Wines",
          "$6 48oz Domestic Pitchers",
        ],
        dow: [
          "saturday",
          "sunday",
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday",
        ],
      },
    ],
  },
  {
    name: "",
    location: "",
    website: "",
    facebook: "",
    instagram: "",
    googleMap: "",
    specials: {
      monday: [],
      tuesday: [],
      wednesday: [],
      thursday: [],
      friday: [],
      saturday: [],
      sunday: [],
    },
    happyHours: [],
  },
];
